import { Platform, StyleSheet } from 'react-native';

const fonts = Platform.select({
  ios: {
    rounded: 'AvenirNextRounded-DemiBold',
    heading: 'AvenirNext-Heavy',
    body: 'AvenirNext-Regular',
  },
  android: {
    rounded: 'sans-serif-rounded',
    heading: 'sans-serif-medium',
    body: 'sans-serif',
  },
  default: {
    rounded: 'ui-rounded, "Nunito", "Avenir Next", system-ui, sans-serif',
    heading: '"Avenir Next", "Inter", system-ui, sans-serif',
    body: '"Inter", "Avenir Next", system-ui, sans-serif',
  },
});

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f7f4f1',
  },
  appShell: {
    flex: 1,
    backgroundColor: '#f7f4f1',
  },
  chatShell: {
    flex: 1,
    backgroundColor: '#f7f4f1',
  },
  chatContent: {
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'web' ? 18 : 12,
    paddingBottom: 144,
    gap: 10,
    minHeight: '100%',
  },
  screen: {
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'web' ? 18 : 12,
    paddingBottom: 78,
    gap: 12,
    minHeight: '100%',
    backgroundColor: '#f7f4f1',
  },
  splashScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 54,
  },
  splashPanel: {
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 18,
    paddingVertical: 20,
    gap: 14,
    shadowColor: '#241f1d',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  splashLogo: {
    backgroundColor: '#222222',
    color: '#ffffff',
    fontFamily: fonts.rounded,
    borderRadius: 5,
    paddingHorizontal: 13,
    paddingVertical: 8,
    fontSize: 22,
    fontWeight: '800',
    overflow: 'hidden',
  },
  splashStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  splashStatus: {
    color: '#5f514b',
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: '600',
  },
  splashTrack: {
    width: '100%',
    height: 4,
    borderRadius: 999,
    backgroundColor: '#efe8e3',
    overflow: 'hidden',
  },
  splashFill: {
    width: '56%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#2563eb',
  },
  topbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  logoMark: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#222222',
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  logo: {
    color: '#ffffff',
    fontFamily: fonts.rounded,
    fontSize: 14,
    fontWeight: '800',
    overflow: 'hidden',
  },
  logoLarge: {
    alignSelf: 'flex-start',
    backgroundColor: '#222222',
    color: '#ffffff',
    fontFamily: fonts.rounded,
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    fontSize: 24,
    fontWeight: '800',
    overflow: 'hidden',
  },
  subtitle: {
    marginTop: 5,
    color: '#74645c',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  authHero: {
    minHeight: 180,
    justifyContent: 'center',
    gap: 12,
  },
  dashboardHero: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 14,
    gap: 7,
  },
  guruHero: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 14,
    gap: 7,
  },
  homeHero: {
    backgroundColor: '#ffffff',
    borderColor: '#93c5fd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 14,
    gap: 7,
    shadowColor: '#241f1d',
    shadowOpacity: 0.03,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  homeHeroFeatured: {
    backgroundColor: '#1d4ed8',
    borderColor: '#1e3a8a',
    borderWidth: 1,
    borderRadius: 6,
    padding: 16,
    gap: 8,
    shadowColor: '#2563eb',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  heroIconBubble: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#dbeafe',
    borderColor: '#bfdbfe',
    borderWidth: 1,
  },
  heroIconBubbleLight: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#fff8fb',
  },
  statusPill: {
    backgroundColor: '#eff6ff',
    color: '#1e40af',
    borderRadius: 4,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '800',
  },
  statusPillLight: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    color: '#ffffff',
    borderRadius: 4,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
  },
  heroEyebrowLight: {
    color: '#ffe2ec',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroTitleLight: {
    color: '#ffffff',
    fontFamily: fonts.rounded,
    fontSize: 23,
    fontWeight: '800',
    lineHeight: 28,
  },
  heroBodyLight: {
    color: '#ffeef4',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
  },
  title: {
    color: '#171312',
    fontFamily: fonts.rounded,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 27,
  },
  body: {
    color: '#5f514b',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
  },
  muted: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 13,
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 13,
    gap: 9,
  },
  formLabel: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  input: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    color: '#241f1d',
    fontFamily: fonts.body,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
  },
  textArea: {
    minHeight: 82,
    textAlignVertical: 'top',
  },
  tabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  tab: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  activeTab: {
    backgroundColor: '#e8f0ea',
    borderColor: '#588364',
  },
  tabText: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '800',
  },
  goalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  goalChip: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: '#ffffff',
  },
  activeChip: {
    backgroundColor: '#e8f0ea',
    borderColor: '#588364',
  },
  chipText: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '700',
  },
  primaryButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    backgroundColor: '#2563eb',
    paddingHorizontal: 12,
    gap: 6,
  },
  heroPrimaryButton: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    backgroundColor: '#2563eb',
    paddingHorizontal: 12,
    gap: 6,
    marginTop: 3,
  },
  heroPrimaryButtonLight: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    gap: 6,
    marginTop: 4,
  },
  heroPrimaryButtonText: {
    color: '#2563eb',
    fontFamily: fonts.rounded,
    fontSize: 14,
    fontWeight: '800',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: fonts.rounded,
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    gap: 6,
  },
  secondaryButtonText: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
  },
  disabled: {
    opacity: 0.48,
  },
  notice: {
    color: '#1e40af',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '700',
  },
  successNotice: {
    alignSelf: 'flex-start',
    backgroundColor: '#e8f0ea',
    color: '#365940',
    borderRadius: 4,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '800',
  },
  actions: {
    flexDirection: 'row',
    gap: 8,
  },
  compactActions: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    gap: 8,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  statStrip: {
    flexDirection: 'row',
    gap: 7,
  },
  metricCard: {
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 10,
    alignItems: 'center',
    gap: 3,
  },
  metricValue: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 18,
    fontWeight: '800',
  },
  workbenchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomColor: '#d8cec8',
    borderBottomWidth: 1,
    paddingBottom: 12,
  },
  workbenchTitle: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '800',
  },
  workbenchMeta: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 18,
  },
  headerActionButton: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderColor: '#2563eb',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
  },
  headerActionText: {
    color: '#2563eb',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
  },
  actionList: {
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  actionRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 11,
    borderBottomColor: '#eee7e3',
    borderBottomWidth: 1,
  },
  actionRowIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#dbeafe',
  },
  actionRowCopy: {
    flex: 1,
    gap: 2,
  },
  actionRowTitle: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 14,
    fontWeight: '800',
  },
  actionRowBody: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionKicker: {
    color: '#6f5e57',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginTop: 1,
    marginBottom: -2,
  },
  summaryPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 12,
    gap: 8,
  },
  inlineEditButton: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
  },
  inlineEditText: {
    color: '#2563eb',
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '800',
  },
  summaryRows: {
    gap: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  summaryLabel: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: '600',
  },
  summaryValue: {
    flex: 1,
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
  },
  logoutButton: {
    alignSelf: 'center',
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
  },
  logoutText: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '700',
  },
  scoreLabel: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
  },
  quizCard: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    gap: 11,
  },
  quizMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  quizSectionPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#eff6ff',
    color: '#1e40af',
    borderRadius: 4,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  eyebrow: {
    color: '#1e40af',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  progressText: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 12,
    fontWeight: '700',
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: '#efe8e3',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#588364',
  },
  signal: {
    color: '#588364',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  question: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 25,
  },
  choiceGrid: {
    gap: 7,
  },
  choice: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 12,
    backgroundColor: '#ffffff',
  },
  activeChoice: {
    borderColor: '#588364',
    backgroundColor: '#e8f0ea',
  },
  choiceText: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 14,
    fontWeight: '700',
  },
  stepperWrap: {
    gap: 10,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 10,
  },
  stepperButton: {
    width: 42,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#2563eb',
  },
  stepperButtonText: {
    color: '#ffffff',
    fontFamily: fonts.rounded,
    fontSize: 21,
    fontWeight: '800',
  },
  stepperValue: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 19,
    fontWeight: '800',
  },
  stepperLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultCover: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 18,
    gap: 12,
  },
  compactResultHero: {
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 12,
    gap: 7,
  },
  resultHeroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  aiBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#e8f0ea',
    color: '#365940',
    fontFamily: fonts.rounded,
    borderRadius: 4,
    fontSize: 10,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textTransform: 'uppercase',
  },
  textButton: {
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    paddingHorizontal: 10,
  },
  textButtonLabel: {
    color: '#1e40af',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  resultTitle: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 31,
  },
  compactResultTitle: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 21,
    fontWeight: '800',
    lineHeight: 25,
  },
  resultBody: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
  },
  scoreRail: {
    gap: 8,
    paddingRight: 16,
  },
  scorePillCard: {
    width: 82,
    minHeight: 58,
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 2,
  },
  scorePillValue: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 18,
    fontWeight: '800',
  },
  segmentedTabs: {
    flexDirection: 'row',
    backgroundColor: '#efe8e3',
    borderRadius: 6,
    padding: 4,
    gap: 4,
  },
  segmentedTab: {
    flex: 1,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    paddingHorizontal: 6,
  },
  activeSegmentedTab: {
    backgroundColor: '#ffffff',
    shadowColor: '#241f1d',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  segmentedTabText: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
  },
  activeSegmentedTabText: {
    color: '#241f1d',
  },
  darkBody: {
    color: '#241f1d',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  shareBar: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 12,
    gap: 8,
    backgroundColor: '#f7f4f1',
  },
  shareText: {
    color: '#241f1d',
    fontFamily: fonts.body,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  shareAction: {
    color: '#1e40af',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 20,
  },
  cardLabel: {
    color: '#1e40af',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  cardText: {
    color: '#74645c',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
  },
  listItem: {
    borderTopColor: '#d8cec8',
    borderTopWidth: 1,
    paddingTop: 8,
    gap: 5,
  },
  exportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  exportPrompt: {
    color: '#365940',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  softBadge: {
    backgroundColor: '#e8f0ea',
    color: '#365940',
    fontFamily: fonts.rounded,
    borderRadius: 4,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '800',
  },
  bottomTabs: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderTopWidth: 1,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: Platform.OS === 'web' ? 7 : 10,
    shadowColor: '#241f1d',
    shadowOpacity: 0.03,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: -2 },
    elevation: 2,
  },
  bottomTab: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    gap: 2,
  },
  primaryBottomTab: {
    marginHorizontal: 2,
    backgroundColor: '#fff6f9',
    borderColor: '#2563eb',
    borderWidth: 1,
  },
  activeBottomTab: {
    backgroundColor: '#2563eb',
    shadowColor: '#2563eb',
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  activePrimaryBottomTab: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  bottomTabLabel: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
  },
  primaryBottomTabLabel: {
    color: '#2563eb',
  },
  activeBottomTabText: {
    color: '#ffffff',
  },
  starterGrid: {
    gap: 7,
  },
  starterPrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
    borderRadius: 6,
    padding: 11,
  },
  starterIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#dbeafe',
  },
  starterPromptText: {
    flex: 1,
    color: '#241f1d',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  chatBubble: {
    maxWidth: '92%',
    borderRadius: 6,
    padding: 11,
    gap: 6,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#2563eb',
  },
  guruBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: '#d8cec8',
    borderWidth: 1,
  },
  chatRole: {
    color: '#74645c',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  chatText: {
    color: '#241f1d',
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  userChatText: {
    color: '#ffffff',
  },
  suggestedTexts: {
    gap: 7,
    marginTop: 3,
  },
  replyOption: {
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 10,
    backgroundColor: '#f7f4f1',
    gap: 7,
  },
  replyOptionText: {
    color: '#241f1d',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  copyMiniButton: {
    alignSelf: 'flex-start',
    borderColor: '#f3cbd8',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: '#ffffff',
  },
  copyMiniText: {
    color: '#2563eb',
    fontFamily: fonts.rounded,
    fontSize: 11,
    fontWeight: '800',
  },
  watchOut: {
    color: '#8f553f',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  nextStep: {
    color: '#365940',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  chatComposer: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: Platform.OS === 'web' ? 78 : 74,
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    backgroundColor: '#ffffff',
    borderColor: '#cfc3bd',
    borderWidth: 1,
    borderRadius: 6,
    padding: 7,
    shadowColor: '#241f1d',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
  },
  chatInput: {
    flex: 1,
    maxHeight: 82,
    color: '#241f1d',
    fontFamily: fonts.body,
    paddingHorizontal: 9,
    paddingVertical: 8,
    fontSize: 14,
  },
  sendButton: {
    minWidth: 60,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#2563eb',
    paddingHorizontal: 10,
    gap: 6,
  },
  sendButtonText: {
    color: '#ffffff',
    fontFamily: fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
  },
});
